# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange


class tradeogre (Exchange):

    def describe(self):
        return self.deep_extend(super(tradeogre, self).describe(), {
            'id': 'tradeogre',
            'name': 'TradeOgre',
            'country': [],
            'rateLimit': 1000,
            'version': '1',
            'comment': 'This comment is optional',
            'urls': {
                'logo': 'https://example.com/image.jpg',
                'api': 'https://tradeogre.com/api/v1',
                'www': 'https://tradeogre.com',
                'doc': [
                    'https://tradeogre.com/help/api',
                ],
            },
            'api': {
                'public': {
                    'get': [
                        'markets',
                        '/orders/{market}',
                        '/ticker/{market}',
                        '/history/{market}',
                    ],
                },
                'private': {
                    'post': [
                    ],
                },
            },
        })

    def nonce(self):
        return self.milliseconds() - self.options['timeDifference']

    def load_time_difference(self):
        response = self.publicGetTime()
        after = self.milliseconds()
        self.options['timeDifference'] = int(after - response['serverTime'])
        return self.options['timeDifference']

    def fetch_markets(self, params={}):
        response = self.publicGetMarkets()
        return response
