<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception as Exception; // a common import

class tradeogre extends Exchange {

    public function describe () {
        return array_replace_recursive (parent::describe (), array (
            'id' => 'tradeogre',
            'name' => 'TradeOgre',
            'country' => [ ],
            'rateLimit' => 1000,
            'version' => '1',
            'comment' => 'This comment is optional',
            'urls' => array (
                'logo' => 'https://example.com/image.jpg',
                'api' => 'https://tradeogre.com/api/v1',
                'www' => 'https://tradeogre.com',
                'doc' => array (
                    'https://tradeogre.com/help/api',
                ),
            ),
            'api' => array (
                'public' => array (
                    'get' => array (
                        'markets',
                        '/orders/{market}',
                        '/ticker/{market}',
                        '/history/{market}',
                    ),
                ),
                'private' => array (
                    'post' => array (
                    ),
                ),
            ),
        ));
    }

    public function nonce () {
        return $this->milliseconds () - $this->options['timeDifference'];
    }

    public function load_time_difference () {
        $response = $this->publicGetTime ();
        $after = $this->milliseconds ();
        $this->options['timeDifference'] = intval ($after - $response['serverTime']);
        return $this->options['timeDifference'];
    }

    public function fetch_markets ($params = array ()) {
        $response = $this->publicGetMarkets ();
        return $response;
    }
}
